sprint10
horseinthesky/metricsagent pull request #15
Opened 2022-12-27 15:53 UTC by horseinthesky

2023-01-06 18:38 UTC, kilchik requested changes

2023-01-06 18:38 UTC, kilchik commented on internal/server/grpc_server.go
> +package server
Я думаю, что в плоской структуре файлов директории server достаточно просто запутаться. Я бы предложил разбить server на два пакета: http и grpc

2023-01-06 18:38 UTC, kilchik commented on internal/server/grpc_update_metrics.go
> +	for _, pbMetric := range req.Metrics {
Очень много дублирующегося кода. Я бы предложил лучше продумать архитектуру. 
Представь, что тебе нужно поддерживать оба интерфейса (grpc и http) всегда в актуальном состоянии, довольно часто возникает требование к сервису предоставлять одну и ту же функциональность по разным протоколам. Когда методы выполняются разным кодом, тебе придется менять код в двух местах, тем самым возрастает вероятность ошибки. 
Подумай в сторону вынесения сущности Server с набором общих методов, выполняющих бизнес логику, и добавления этой сущности в атрибуты GRPCServer и HTTPServer, в которых будет выполняться только формирование входных параметров для методов Server и разбор результатов их выполнения.
Так тебе удастся инкапсулировать все зависимости (как например слой БД) в Server, а GRPCServer и HTTPServer будут взаимодействовать с ним по заданному тобой интерфейсу

2023-01-08 08:05 UTC, horseinthesky commented on internal/server/grpc_update_metrics.go
> +	for _, pbMetric := range req.Metrics {
Я понимаю. Ввиду того, что gRPC в проекте появился на закате программы, я просто не успел за один инкремент переписать всю архитектуру, что делал 5 месяцев =)

В реальном проекте у нас был бы gRPC Gateway и код для него также генерировался бы protoc автоматом.

Я попробую что-то тут успеть за оставшееся до диплома время.

2023-01-12 18:47 UTC, closed without merging