Sprint2v4
horseinthesky/metricsagent pull request #5
Opened 2022-08-29 21:26 UTC by horseinthesky

2022-08-31 16:12 UTC, rekby requested changes

2022-08-31 16:12 UTC, rekby commented on cmd/agent/main.go
> +	if err := env.Parse(cfg); err != nil {
Сначала парсить переменные окружения в конфиг через библиотеку, потом ещё раз руками - странно. Когда что-то пойдёт не так - непонятно где искать проблему.

Удобнее будет сначала распарсить части конфига через флаги, затем ещё раз - через env.Parse, тогда повторяющиеся значения перезапишутся из переменных окружения.

2022-08-31 16:12 UTC, rekby commented on cmd/agent/main.go
> +	address        *string
Параметры запуска дублируются в отдельных глобальных переменных и в cfg, в итоге непонятно что будет использоваться для реальной работы.

Лучше отказаться от глобальных перменных и заполнять только конфиг (локальный экземпляр, передавать в функции как параметр)

2022-08-31 16:12 UTC, rekby commented on cmd/agent/main.go
> +	cfg            = &agent.Config{}
переменную data тоже лучше объявить локально.

глобальных перменных стоит избегать до последнего - чаще всего они заметно затрудняют диагностику проблем ипонимание схемы работы сервиса, затрудняют его доработки.

2022-08-31 16:12 UTC, rekby commented on cmd/server/main.go
> +	defaultStoreInterval = time.Duration(300 * time.Second)
тут и в подобных местах типы можно не приводить - из time.Second очевидно что это будет time.Duration, а целочисланная константа сама принимает нужный тип.

2022-08-31 16:12 UTC, rekby commented on cmd/agent/main.go
> +			agent.SendMetricsJSON()
Опционально: Эти циклы лучше унести внутри agent. Чтобы тикеры и их использование оказались рядом и вероятно их вообще можно будет сделать приватными.

Чем меньше данных в общей области видимости - тем лучше, т.к. позволяет проще менять реализацию в будущем.

2022-08-31 16:12 UTC, rekby commented on internal/server/backup.go
> +func (b Backuper) WriteMetrics(metrics *[]storage.Metric) error {
Передавать слайсы по указателю имеет смысл только если нужно менять длину слайса, в остальных случаях слайс передаётся по значению.

Сам слайс содержит внутри ссылку на реальный массив с данными и при его передаче по значению копируется только небольшая структура вместе с указателем. Данные, хранящиеся в слайсе не копируются.

2022-08-31 16:12 UTC, rekby commented on internal/server/handlers.go
> +		tmpl.Execute(w, floatedMetrics)
Тут имеет смысл проверить ошибку и если шаблон не отрендерился (например ошибка в шаблоне) - залогировать её.

А ещё лучше сначала отрендерить во внутренний буфер и ответ возвращать только если ошибок нет (а если есть - вернуть код ошибки)

2022-08-31 16:12 UTC, rekby commented on internal/server/handlers.go
> +			os.Exit(1)
При недостающем файле имеет смысл вернуть код ошибки клиету, а не завершать всё приложение целиком, т.к. сервер полезен и без дашборда - в него могут отправлять метрики, сервер их будет сохранять и отдавать по API.

Остановка всей программы имеет смысл когда ошибка серьёзная и продолжать дальше работу опасно или нет смысла совсем.

2022-08-31 16:12 UTC, rekby commented on internal/server/middleware.go
> +			io.WriteString(w, err.Error())
тут нужно не только записать текст ошибки в вывод, но и поставить код ошибки для возврата клиенту, иначе он получить строку с ошибкой и код 200 (т.е. с формальной т.з. ответ сервера будет считаться правильным).
Это затруднит обработку ошибок со стороны клиента.

2022-08-31 16:12 UTC, rekby commented on internal/server/middleware.go
> +	"io/ioutil"
В новом коде лучше использовать пакет io, функционал примерно тот же, но лучше организовано и считается рекомендованным к использованию начиная с go 1.16

2022-08-31 19:02 UTC, horseinthesky commented on cmd/server/main.go
> +	defaultStoreInterval = time.Duration(300 * time.Second)
Имеешь в виду, оборачивать в `time.Duration` не обязательно?

2022-08-31 19:08 UTC, horseinthesky commented on cmd/agent/main.go
> +			agent.SendMetricsJSON()
Унёс цикл в `internal/agent` под функцию `Run`.

2022-08-31 19:08 UTC, horseinthesky commented on internal/server/backup.go
> +func (b Backuper) WriteMetrics(metrics *[]storage.Metric) error {
Готово.

2022-08-31 19:21 UTC, horseinthesky commented on internal/server/handlers.go
> +		tmpl.Execute(w, floatedMetrics)
Добавил обработку ошибок парсинга и рендеринга шаблона.

2022-08-31 19:23 UTC, horseinthesky commented on internal/server/handlers.go
> +			os.Exit(1)
Добавил обработку ошибок чтения файла шаблона.

2022-08-31 19:25 UTC, horseinthesky commented on internal/server/middleware.go
> +			io.WriteString(w, err.Error())
Добавил код через:
```
http.Error(w, err.Error(), http.StatusBadRequest)
```

2022-08-31 19:26 UTC, horseinthesky commented on internal/server/middleware.go
> +	"io/ioutil"
Убрал `ioutil`.

2022-08-31 20:22 UTC, horseinthesky commented on cmd/agent/main.go
> +	if err := env.Parse(cfg); err != nil {
Переделал.

2022-08-31 20:22 UTC, horseinthesky commented on cmd/agent/main.go
> +	address        *string
Сделал.

2022-09-01 18:42 UTC, rekby commented on cmd/server/main.go
> +	defaultStoreInterval = time.Duration(300 * time.Second)
Да

2022-09-01 18:55 UTC, rekby approved these changes

2022-09-01 18:55 UTC, rekby commented on cmd/agent/main.go
> +	time.Sleep(200 * time.Millisecond)
Просто для информации:

С такого рода паузами есть проблема: почти всегда это гонка, которая  обычно завершается успешно.

Но без гарантий - например на сильно загруженном процессоре 200мс может нехватить и процесс завершится раньше, чем агент завершит свою работу (в случае агента это не страшно, т.к. он данные никуда не пишет).

В случае если бы тут было сохранение в файл - процесс мог бы оборвать запись на середине файла и он бы получился битым.

Обычно делают что-то вроде функции Close() error/Shutdown(ctx) error

Функции синхронные и ждут завершения процессов. Close - ждёт до победного, Shutdown - пока не отменится контекст.

2022-09-01 18:55 UTC, rekby commented on internal/server/handlers.go
> +			log.Printf("failed to read dashboard template file: %s", err)
Такая обработка ошибок уже лучше - в логах останется информация о проблеме и сервис продолжит работать.

Просто для информации:
В функциях ниже по файлу есть пример с возвратом клиенту статуса ошибки выполнения запроса.
Обычно хорошо эти два сопосба совмещать - чтобы и в логах подробности оставались и клиент получал код ошики выполнения запроса и смог как-то обработать это на своей стороне.

2022-09-01 19:56 UTC, merged